### ISSUE TITLE
Reverse String

### ISSUE THREAD

**Issue by Zohaib-Sathio** [Zohaib-Sathio/Hacktoberfest_22#1]
add a program which reverses the input string and returns it.

**Comment by Ishantgarg-web** [comment]
Please assign this to me under hactoberfest2022

**Comment by rahul-n18** [comment]
Hello @Zohaib-Sathio can you assign me this

**Comment by Zohaib-Sathio** [comment]
> Please assign this to me under hactoberfest2022

@Ishantgarg-web I can assign you the other issue in this repo

**Comment by Zohaib-Sathio** [comment]
> Hello @Zohaib-Sathio can you assign me this

@rahul-n18 assigned.

**Comment by rahul-n18** [comment]
Hello @Zohaib-Sathio I just wanted to confirm that I need to add reverse a string prg in all the language right?

**Comment by Zohaib-Sathio** [comment]
> Hello @Zohaib-Sathio I just wanted to confirm that I need to add reverse a string prg in all the language right?

@rahul-n18 it's upto you, I would suggest to add your program in any one language.

**Comment by rahul-n18** [comment]
I hope you can close this issue.
Its my first time here now do I get Hactoberfest accepted badge for this

**Comment by Zohaib-Sathio** [comment]
> I hope you can close this issue. Its my first time here now do I get Hactoberfest accepted badge for this

Yes @rahul-n18 I have added label to your accepted PR.

**Comment by Saurabhk1975** [comment]
please assign me this @Zohaib-Sathio
