### ISSUE TITLE
Sorting Algorithm in C++

### ISSUE THREAD

**Issue by Zohaib-Sathio** [Zohaib-Sathio/Hacktoberfest_22#26]
Add any one Sorting Algorithm of C++ language

**Comment by ENVIRYO2112VIT** [comment]
Hi @Zohaib-Sathio , please assign this issue to me.

**Comment by ENVIRYO2112VIT** [comment]
I am interested in working on this issue! Thank you!

**Comment by Zohaib-Sathio** [comment]
> I am interested in working on this issue! Thank you!

Assigned.

**Comment by ENVIRYO2112VIT** [comment]
Hi @Zohaib-Sathio !
Created the PR for the issue.
Please verify it and merge the same.

Do let me know if any changes required

Thank you!

**Comment by Faizan96322** [comment]
hey, can you please assign me this task, I would like to contribute

**Comment by ENVIRYO2112VIT** [comment]
@Zohaib-Sathio 
Pull Request #43
