### ISSUE TITLE
Sorting Algorithm of Java

### ISSUE THREAD

**Issue by Zohaib-Sathio** [Zohaib-Sathio/Hacktoberfest_22#27]
Add any one Sorting Algorithm of Java language

**Comment by Animesht1008** [comment]
hi @Zohaib-Sathio  can you please assign it to me under the label of Hacktoberfest accepted and Hacktoberfest 2022

**Comment by Zohaib-Sathio** [comment]
> hi @Zohaib-Sathio can you please assign it to me under the label of Hacktoberfest accepted and Hacktoberfest 2022

Assigned.

**Comment by Zohaib-Sathio** [comment]
@Animesht1008 Thank you for contributing, Happy hacking!
