### ISSUE TITLE
Sorting Algorithm in Python

### ISSUE THREAD

**Issue by Zohaib-Sathio** [Zohaib-Sathio/Hacktoberfest_22#28]
Add an Sorting Algorithm in Python language

**Comment by Animesht1008** [comment]
hi @Zohaib-Sathio  can you please assign it to me under the label of Hacktoberfest accepted and Hacktoberfest 2022

**Comment by Zohaib-Sathio** [comment]
> hi @Zohaib-Sathio can you please assign it to me under the label of Hacktoberfest accepted and Hacktoberfest 2022

Assigned.
