### ISSUE TITLE
Find longest common Subsequence String

### ISSUE THREAD

**Issue by Zohaib-Sathio** [Zohaib-Sathio/Hacktoberfest_22#29]
Write an algorithm to find longest Common Subsequence String

**Comment by Animesht1008** [comment]
hi @Zohaib-Sathio  can you please assign it to me under the label of Hacktoberfest accepted and Hacktoberfest 2022

**Comment by Gulshan-11** [comment]
hiii @Zohaib-Sathio can you assign this to me

**Comment by Zohaib-Sathio** [comment]
@Gulshan-11 @Animesht1008 I have assigned you both this issue

**Comment by shaneahmad** [comment]
Please assign this issue to me.
