### ISSUE TITLE
Program to find Height of Binary Tree

### ISSUE THREAD

**Issue by Zohaib-Sathio** [Zohaib-Sathio/Hacktoberfest_22#30]
Write a Program to find Height of Binary Tree

**Comment by aiden5221** [comment]
Please assign this to me.

**Comment by Zohaib-Sathio** [comment]
> Please assign this to me.

Assigned.

**Comment by Gulshan-11** [comment]
hey @Zohaib-Sathio pleasee assign this to me

**Comment by Zohaib-Sathio** [comment]
> hey @Zohaib-Sathio pleasee assign this to me

@Gulshan-11 Assigned to you also.

**Comment by Gulshan-11** [comment]
Hey @Zohaib-Sathio Please check the Pr for  finding height
closes #42

**Comment by Zohaib-Sathio** [comment]
> Hey @Zohaib-Sathio Please check the Pr for finding height closes #42

I have requested some changes kindly do them then after merging your PR I will be closing this issue don't worry.
