### ISSUE TITLE
Integer array without duplicates

### ISSUE THREAD

**Issue by Zohaib-Sathio** [Zohaib-Sathio/Hacktoberfest_22#31]
A program given an input integer array which then returns an integer array without any duplicates

**Comment by AaryanSingh0017** [comment]
Plz assign me under the label hacktoberfest accepted

**Comment by Zohaib-Sathio** [comment]
> Plz assign me under the label hacktoberfest accepted

@AaryanSingh0017 assigned to you but will add accepted label on your PR.

**Comment by AaryanSingh0017** [comment]
where should i put the file and what should be the name?

**Comment by Zohaib-Sathio** [comment]
> where should i put the file and what should be the name?

Whatever language it is in go in that directory then data structures/Array
