### ISSUE TITLE
Find maximum number in an array

### ISSUE THREAD

**Issue by Zohaib-Sathio** [Zohaib-Sathio/Hacktoberfest_22#32]
A program which finds maximum number in an array

**Comment by Animesht1008** [comment]
hi @Zohaib-Sathio  can you please assign it to me under the label of Hacktoberfest accepted and Hacktoberfest 2022

**Comment by ENVIRYO2112VIT** [comment]
Hello @Zohaib-Sathio !
I am interested in working on this issue. 
Please asign this to me!
Thanks

**Comment by Zohaib-Sathio** [comment]
> Hello @Zohaib-Sathio ! I am interested in working on this issue. Please asign this to me! Thanks

@ENVIRYO2112VIT Assigned to you.

**Comment by ENVIRYO2112VIT** [comment]
Thank you!

**Comment by ENVIRYO2112VIT** [comment]
Hi @Zohaib-Sathio !
I have created the PR by adding the desired program.
Please look into it. I will be waiting for any suggested changes from your side.
Thank you!

**Comment by Zohaib-Sathio** [comment]
Thank you @ENVIRYO2112VIT for contributing, I have reviewed and merged your PR to the repo and labeled it also.
