### ISSUE TITLE
Merge Two sorted array

### ISSUE THREAD

**Issue by Zohaib-Sathio** [Zohaib-Sathio/Hacktoberfest_22#33]
A program which merges two sorted arrays

**Comment by Animesht1008** [comment]
hi @Zohaib-Sathio  can you please assign it to me under the label of Hacktoberfest accepted and Hacktoberfest 2022

**Comment by vickyaryan7** [comment]
merge my pr and also assign to me

**Comment by vickyaryan7** [comment]
thanks @Zohaib-Sathio

**Comment by Zohaib-Sathio** [comment]
> thanks @Zohaib-Sathio

@pwnb0y Welcome :)
