### ISSUE TITLE
Total sum of the Binary Tree

### ISSUE THREAD

**Issue by Zohaib-Sathio** [Zohaib-Sathio/Hacktoberfest_22#35]
A program which finds total sum of the binary tree

**Comment by Animesht1008** [comment]
hi @Zohaib-Sathio  can you please assign it to me under the label of Hacktoberfest accepted and Hacktoberfest 2022

**Comment by AaryanSingh0017** [comment]
assign me as well

**Comment by Zohaib-Sathio** [comment]
> hi @Zohaib-Sathio can you please assign it to me under the label of Hacktoberfest accepted and Hacktoberfest 2022

@Animesht1008 Sorry I can not assign you more than 3 issues at a time, kindly resolve the first assigned.

**Comment by Zohaib-Sathio** [comment]
> assign me as well

@AaryanSingh0017 Assigned to you.

**Comment by Faizan96322** [comment]
hey, @Zohaib-Sathio please assign me this task if @AaryanSingh0017 is not working on it!
