### ISSUE TITLE
Simple Calculator GUI using Java 

### ISSUE THREAD

**Issue by smilewithkhushi** [Zohaib-Sathio/Hacktoberfest_22#52]
Hi, I want to add a simple Calculator GUI program using Java Swing.

I'm new to contributions. I hope you would assign this issue to me : )

**Comment by Zohaib-Sathio** [comment]
> Hi, I want to add a simple Calculator GUI program using Java Swing.
> 
> I'm new to contributions. I hope you would assign this issue to me : )

Sorry @smilewithkhushi But GUI Calculator using Java has already been contributed by other contributor. you can contribute any other program or any small project other than calculator.

**Comment by smilewithkhushi** [comment]
okay, thank you for letting me know.
