### ISSUE TITLE
I want to add Java Program of BMI Calculator

### ISSUE THREAD

**Issue by minhaj-313** [Zohaib-Sathio/Hacktoberfest_22#61]
BMI calculator is Used to find Body Mass Index.
Please Assign me Under Hacktoberfest

**Comment by Zohaib-Sathio** [comment]
> BMI calculator is Used to find Body Mass Index. Please Assign me Under Hacktoberfest

Assigned.

**Comment by minhaj-313** [comment]
> > BMI calculator is Used to find Body Mass Index. Please Assign me Under Hacktoberfest
> 
> Assigned.

Thank You
