### ISSUE TITLE
Data Structure Queue manipulation using C++

### ISSUE THREAD

**Issue by smilewithkhushi** [Zohaib-Sathio/Hacktoberfest_22#66]
Implementation of Queue using Array, Linkedlist and templates along with the proper functionality of queue (i.e, insertion, deletion, updation)

**Comment by Zohaib-Sathio** [comment]
> Implementation of Queue using Array, Linkedlist and templates along with the proper functionality of queue (i.e, insertion, deletion, updation)

Assigned.

**Comment by smilewithkhushi** [comment]
thank you so much!
