### ISSUE TITLE
Sum of the Array in Python without in-built methods

### ISSUE THREAD

**Issue by Zohaib-Sathio** [Zohaib-Sathio/Hacktoberfest_22#68]
Write a program to calculate the total Sum of the Array in Python

**Comment by ArshErgon** [comment]
```
def sum_of_array(array):
      return sum(array)
```
its pretty easy for hacktoberfest

**Comment by Zohaib-Sathio** [comment]
> ```
> def sum_of_array(array):
>       return sum(array)
> ```
> 
> its pretty easy for hacktoberfest

@ArshErgon I have changed requirement a bit but remember this issue for new comers.

**Comment by AnupeshVerma** [comment]
can you plz assign this issue to me ?

**Comment by AnupeshVerma** [comment]
!assign

**Comment by anupeshverma** [comment]
!assign

**Comment by Zohaib-Sathio** [comment]
@anupeshverma Assigned.
