### ISSUE TITLE
Sum of the Array in C++

### ISSUE THREAD

**Issue by Zohaib-Sathio** [Zohaib-Sathio/Hacktoberfest_22#69]
Write a program to calculate the total Sum of the Array in C++

**Comment by Chanchal14-creator** [comment]
please assign me this issue

**Comment by Zohaib-Sathio** [comment]
> please assign me this issue

Assigned.

**Comment by anupeshverma** [comment]
can you plz assign this issue to me ?

**Comment by AnupeshVerma** [comment]
!assign
