### ISSUE TITLE
Is Number Prime?

### ISSUE THREAD

**Issue by Zohaib-Sathio** [Zohaib-Sathio/Hacktoberfest_22#75]
Program which tells whether the given number is a prime number or not

**Comment by Samarthasbhat** [comment]
Assign me i will do this

**Comment by Zohaib-Sathio** [comment]
> Assign me i will do this

Assigned.

**Comment by Samarthasbhat** [comment]
where i should add the program

**Comment by Samarthasbhat** [comment]
i will add it in other programs

**Comment by Samarthasbhat** [comment]
@Zohaib-Sathio

**Comment by Zohaib-Sathio** [comment]
> @Zohaib-Sathio

@Samarthasbhat Yes, Place the file in other programs.

**Comment by Samarthasbhat** [comment]
I have added it please merge it @Zohaib-Sathio

**Comment by Zohaib-Sathio** [comment]
> I have added it please merge it @Zohaib-Sathio

I don't see any PR related to this issue!

**Comment by Samarthasbhat** [comment]
now see it is on the java others program as prime.java

**Comment by Samarthasbhat** [comment]
@Zohaib-Sathio  i have now created pull request

**Comment by shaneahmad** [comment]
Please Assign this issue to me

**Comment by AnupeshVerma** [comment]
can you assign this issue to me
